version: '3.4'

networks:
  polkanalysis_network:
    driver: bridge

volumes:
  polkanalysis_data:
    driver: local

services:
  polkanalysis.worker:
    container_name: Polkanalysis_Worker
    image: ${DOCKER_REGISTRY-}polkanalysis.worker
    build:
      context: .
      dockerfile: worker.dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    networks:
      - polkanalysis_network

  db:
    container_name: Polkanalysis_Database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    expose:
    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
    - "5433:5433"
    command: -p 5433
    volumes:
      - polkanalysis_data:/var/lib/postgresql/data
    networks:
      - polkanalysis_network

