version: '3.4'

networks:
  polkanalysis_network:
    driver: bridge

volumes:
  polkanalysis_data:
    driver: local

services:
  polkanalysis.api:
    container_name: Polkanalysis_Api
    image: ${DOCKER_REGISTRY-}polkanalysis.api
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - polkanalysis_network
    
  polkanalysis.webapp:
    container_name: Polkanalysis_WebApp
    image: ${DOCKER_REGISTRY-}polkanalysis.webapp
    build:
      context: .
      dockerfile: webapp.dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - polkanalysis_network

  db:
    container_name: Polkanalysis_Database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    expose:
    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
    - "5433:5433"
    command: -p 5433
    volumes:
      - polkanalysis_data:/var/lib/postgresql/data
    networks:
      - polkanalysis_network
