version: '3.4'

networks:
  polkanalysis_network:
    driver: bridge

volumes:
  polkanalysis_data:
    driver: local

services:
  polkanalysis.worker:
    container_name: Polkanalysis_Worker
    image: ${DOCKER_REGISTRY-}polkanalysis.worker
    build:
      context: .
      dockerfile: worker.dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    networks:
      - polkanalysis_network

  db:
    container_name: Polkanalysis_Database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    expose:
    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
    - "5433:5433"
    command: -p 5433
    volumes:
      - polkanalysis_data:/var/lib/postgresql/data
    networks:
      - polkanalysis_network

  prometheus:
    container_name: Polkanalysis_Prometheus
    build:
      context: ./docker/prometheus
    depends_on:
      - polkanalysis.worker
    ports:
      - 9090:9090
    networks:
      - polkanalysis_network

  grafana:
    container_name: Polkanalysis_Grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - polkanalysis_network

  otel-collector:
    container_name: Polkanalysis_OtelCollector
    image: otel/opentelemetry-collector:0.97.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      - polkanalysis_network

