//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Polkanalysis.Domain.Contracts.Core.Display;
using Polkanalysis.Infrastructure.Blockchain.Internal.Scan.Mapping;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v2.Enums
{
    [DomainMapping("xcm/v2/junction")]
    public enum Junction
    {
        Parachain = 0,
        AccountId32 = 1,
        AccountIndex64 = 2,
        AccountKey20 = 3,
        PalletInstance = 4,
        GeneralIndex = 5,
        GeneralKey = 6,
        OnlyChild = 7,
        Plurality = 8
    }

    /// <summary>
    /// >> 15935 - Variant[xcm.v2.junction.Junction]
    /// </summary>
    public sealed class EnumJunction : BaseEnumExt<Junction, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U32>, BaseTuple<EnumNetworkId, NameableSize32>, BaseTuple<EnumNetworkId, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U64>>, BaseTuple<EnumNetworkId, NameableSize20>, Substrate.NetApi.Model.Types.Primitive.U8, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U128>, Substrate.NetApi.Model.Types.Base.BaseVec<Substrate.NetApi.Model.Types.Primitive.U8>, BaseVoid, BaseTuple<EnumBodyId, EnumBodyPart>>
    {
    }
}