//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.System;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3
{
    public enum WeightLimit
    {
        Unlimited = 0,
        Limited = 1
    }

    /// <summary>
    /// >> 16801 - Variant[xcm.v3.WeightLimit]
    /// </summary>
    public sealed class EnumWeightLimit : BaseEnumExt<WeightLimit, BaseVoid, Weight>
    {
    }
}