//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3
{
    public enum Response
    {
        Null = 0,
        Assets = 1,
        ExecutionResult = 2,
        Version = 3,
        PalletsInfo = 4,
        DispatchResult = 5
    }

    /// <summary>
    /// >> 16786 - Variant[xcm.v3.Response]
    /// </summary>
    public sealed class EnumResponse : BaseEnumExt<Response, BaseVoid, MultiAssets, Substrate.NetApi.Model.Types.Base.BaseOpt<Substrate.NetApi.Model.Types.Base.BaseTuple<Substrate.NetApi.Model.Types.Primitive.U32, Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3.Enums.EnumError>>, Substrate.NetApi.Model.Types.Primitive.U32, Substrate.NetApi.Model.Types.Base.BaseVec<PalletInfo>, EnumMaybeErrorCode>
    {
    }
}