//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Polkanalysis.Domain.Contracts.Core.Display;
using Polkanalysis.Infrastructure.Blockchain.Internal.Scan.Mapping;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3.Enums
{
    [DomainMapping("xcm/v3/junction")]
    public enum Junction
    {
        Parachain = 0,
        AccountId32 = 1,
        AccountIndex64 = 2,
        AccountKey20 = 3,
        PalletInstance = 4,
        GeneralIndex = 5,
        GeneralKey = 6,
        OnlyChild = 7,
        Plurality = 8,
        GlobalConsensus = 9
    }

    /// <summary>
    /// >> 16537 - Variant[xcm.v3.junction.Junction]
    /// </summary>
    public sealed class EnumJunction : BaseEnumExt<Junction, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U32>, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseOpt<EnumNetworkId>, NameableSize32>, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseOpt<EnumNetworkId>, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U64>>, BaseTuple<Substrate.NetApi.Model.Types.Base.BaseOpt<EnumNetworkId>, NameableSize20>, Substrate.NetApi.Model.Types.Primitive.U8, Substrate.NetApi.Model.Types.Base.BaseCom<Substrate.NetApi.Model.Types.Primitive.U128>, BaseTuple<Substrate.NetApi.Model.Types.Primitive.U8, NameableSize32>, BaseVoid, BaseTuple<EnumBodyId, EnumBodyPart>, EnumNetworkId>
    {
    }
}