//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.PolkadotPrimitive.v2;
using Substrate.NetApi.Model.Types.Base;


namespace Polkanalysis.Domain.Contracts.Secondary.Pallet.PolkadotPrimitive.v2.Enum
{


    public enum CoreOccupied
    {
        
        Parathread = 0,
        
        Parachain = 1,
    }
    
    /// <summary>
    /// >> 661 - Variant[polkadot_primitives.v2.CoreOccupied]
    /// </summary>
    public sealed class EnumCoreOccupied : BaseEnumExt<CoreOccupied, ParathreadEntry, BaseVoid>
    {
    }
}
