using Ajuna.NetApi.Model.Types;
using Ajuna.NetApi.Model.Types.Base;
using Blazscan.Polkadot.NetApiExt.Generated;

namespace Blazscan.Domain.Contracts.Repository
{
    public interface ISubstrateNodeRepository
    {
        /// <summary>
        /// Substrate client generated by the Ajuna SDK
        /// </summary>
        public SubstrateClientExt Client { get; }

        /// <summary>
        /// Get storage from Substrate
        /// Temporary while Ajuna allow querying with a given block Hash
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="parameters"></param>
        /// <param name="token"></param>
        /// <returns></returns>
        public Task<T> GetStorageAsync<T>(string parameters, Hash? blockHash, CancellationToken token) where T : IType, new();

        /// <summary>
        /// Check every 'millisecondCheck' if we are connected to blockchain and call the callback method with status
        /// If we are not connected, try to reconnect
        /// </summary>
        /// <param name="isConnectedCallback">Callback status method</param>
        /// <param name="cancellationToken">Allow to stop the check</param>
        /// <param name="millisecondCheck">Millisecond frequency to check if we are connected and try to reconnect</param>
        /// <returns></returns>
        Task CheckBlockchainStateAsync(Action<bool> isConnectedCallback, CancellationToken cancellationToken, int millisecondCheck = 500);
    }
}
