// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Polkanalysis.Infrastructure.Database;

#nullable disable

namespace Polkanalysis.Infrastructure.Common.Migrations
{
    [DbContext(typeof(SubstrateDbContext))]
    partial class SubstrateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Blocks.BlockInformationModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EventsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtrinsicsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<long>("LogsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidatorAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlockchainName", "BlockNumber");

                    b.ToTable("BlockInformation");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Errors.SubstrateErrorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BlockchainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ElementId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeError")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubstrateErrors");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Auctions.AuctionsAuctionClosedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("AuctionIndex")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AuctionIndex");

                    b.ToTable("EventAuctionsAuctionClosed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Auctions.AuctionsAuctionStartedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("AuctionIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("LeasePeriod")
                        .HasColumnType("bigint");

                    b.Property<long>("Ending")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AuctionIndex", "LeasePeriod", "Ending");

                    b.ToTable("EventAuctionsAuctionStarted");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesBalanceSetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("RootAccount")
                        .HasColumnType("text");

                    b.Property<double>("Amount1")
                        .HasColumnType("double precision");

                    b.Property<double>("Amount2")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "RootAccount", "Amount1", "Amount2");

                    b.ToTable("EventBalancesBalanceSet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesDustLostModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress", "Amount");

                    b.ToTable("EventBalancesDustLost");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesEndowedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress", "Amount");

                    b.ToTable("EventBalancesEndowed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesReservedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<double>("ReservedAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress", "ReservedAmount");

                    b.ToTable("EventBalancesReserved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesSlashedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddess")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddess", "Amount");

                    b.ToTable("EventBalancesSlashed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesTransferModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "From", "To", "Amount");

                    b.ToTable("EventBalancesTransfer");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Balances.BalancesUnreservedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddess")
                        .HasColumnType("text");

                    b.Property<double>("UnreservedAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddess", "UnreservedAmount");

                    b.ToTable("EventBalancesUnreserved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Crowdloan.CrowdloanContributedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddess")
                        .HasColumnType("text");

                    b.Property<long>("CrowdloanId")
                        .HasColumnType("bigint");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddess", "CrowdloanId", "Amount");

                    b.ToTable("EventCrowdloanContributed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Crowdloan.CrowdloanCreatedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("CrowdloanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "CrowdloanId");

                    b.ToTable("EventCrowdloanCreated");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.EventManagerModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastOccurenceScannedBlockId")
                        .HasColumnType("integer");

                    b.Property<int>("LastScanBlockId")
                        .HasColumnType("integer");

                    b.HasKey("BlockchainName", "ModuleName", "ModuleEvent");

                    b.ToTable("EventManager");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.EventsInformationModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BlockchainName", "BlockId", "EventId");

                    b.ToTable("EventsInformation");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Identity.IdentityIdentityClearedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress", "Amount");

                    b.ToTable("EventIdentityIdentityCleared");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Identity.IdentityIdentityKilledModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress", "Amount");

                    b.ToTable("EventIdentityIdentityKilled");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Identity.IdentityIdentitySetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress");

                    b.ToTable("EventIdentityIdentitySet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsAllApprovalsCancelledModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Owner");

                    b.ToTable("EventNftsAllApprovalsCancelled");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsApprovalCancelledModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Delegate")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Owner", "Delegate");

                    b.ToTable("EventNftsApprovalCancelled");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsBurnedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Owner");

                    b.ToTable("EventNftsBurned");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionConfigChangedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection");

                    b.ToTable("EventNftsCollectionConfigChanged");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionLockedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection");

                    b.ToTable("EventNftsCollectionLocked");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionMaxSupplySetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<double>("Max_supply")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Max_supply");

                    b.ToTable("EventNftsCollectionMaxSupplySet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionMetadataClearedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection");

                    b.ToTable("EventNftsCollectionMetadataCleared");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionMetadataSetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Data");

                    b.ToTable("EventNftsCollectionMetadataSet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCollectionMintSettingsUpdatedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection");

                    b.ToTable("EventNftsCollectionMintSettingsUpdated");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsCreatedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Creator", "Owner");

                    b.ToTable("EventNftsCreated");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsDestroyedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection");

                    b.ToTable("EventNftsDestroyed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsForceCreatedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Owner");

                    b.ToTable("EventNftsForceCreated");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsIssuedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Owner");

                    b.ToTable("EventNftsIssued");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemAttributesApprovalAddedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Delegate")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Delegate");

                    b.ToTable("EventNftsItemAttributesApprovalAdded");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemAttributesApprovalRemovedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<string>("BlockchainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Delegate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventNftsItemAttributesApprovalRemoved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemBoughtModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Seller")
                        .HasColumnType("text");

                    b.Property<string>("Buyer")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Price", "Seller", "Buyer");

                    b.ToTable("EventNftsItemBought");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemMetadataClearedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item");

                    b.ToTable("EventNftsItemMetadataCleared");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemMetadataSetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Data");

                    b.ToTable("EventNftsItemMetadataSet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemPriceRemovedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item");

                    b.ToTable("EventNftsItemPriceRemoved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemPriceSetModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Whitelisted_buyer")
                        .HasColumnType("text");

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Price");

                    b.ToTable("EventNftsItemPriceSet");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemPropertiesLockedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<bool>("Lock_metadata")
                        .HasColumnType("boolean");

                    b.Property<bool>("Lock_attributes")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Lock_metadata", "Lock_attributes");

                    b.ToTable("EventNftsItemPropertiesLocked");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemTransferLockedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item");

                    b.ToTable("EventNftsItemTransferLocked");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsItemTransferUnlockedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item");

                    b.ToTable("EventNftsItemTransferUnlocked");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsNextCollectionIdIncrementedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Next_id")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Next_id");

                    b.ToTable("EventNftsNextCollectionIdIncremented");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsOwnerChangedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("New_owner")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "New_owner");

                    b.ToTable("EventNftsOwnerChanged");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsTeamChangedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<string>("Admin")
                        .HasColumnType("text");

                    b.Property<string>("Freezer")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Issuer", "Admin", "Freezer");

                    b.ToTable("EventNftsTeamChanged");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsTipSentModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Receiver")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Sender", "Receiver", "Amount");

                    b.ToTable("EventNftsTipSent");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsTransferApprovedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Delegate")
                        .HasColumnType("text");

                    b.Property<long>("Deadline")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "Owner", "Delegate", "Deadline");

                    b.ToTable("EventNftsTransferApproved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Nfts.NftsTransferredModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<double>("Collection")
                        .HasColumnType("double precision");

                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Collection", "Item", "From", "To");

                    b.ToTable("EventNftsTransferred");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsBondedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("Member")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Bonded")
                        .HasColumnType("double precision");

                    b.Property<bool>("Joined")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Member", "Pool_id", "Bonded", "Joined");

                    b.ToTable("EventNominationPoolsBonded");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsCreatedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("Depositor")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Depositor", "Pool_id");

                    b.ToTable("EventNominationPoolsCreated");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsDestroyedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Pool_id");

                    b.ToTable("EventNominationPoolsDestroyed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsMemberRemovedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Member")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Pool_id", "Member");

                    b.ToTable("EventNominationPoolsMemberRemoved");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsMinBalanceDeficitAdjustedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Pool_id", "Amount");

                    b.ToTable("EventNominationPoolsMinBalanceDeficitAdjusted");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsMinBalanceExcessAdjustedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Pool_id", "Amount");

                    b.ToTable("EventNominationPoolsMinBalanceExcessAdjusted");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsPaidOutModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("Member")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Payout")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Member", "Pool_id", "Payout");

                    b.ToTable("EventNominationPoolsPaidOut");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsPoolCommissionClaimedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Pool_id", "Commission");

                    b.ToTable("EventNominationPoolsPoolCommissionClaimed");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsUnbondedModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("Member")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<long>("Era")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Member", "Pool_id", "Balance", "Points", "Era");

                    b.ToTable("EventNominationPoolsUnbonded");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.NominationPools.NominationPoolsWithdrawnModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("Member")
                        .HasColumnType("text");

                    b.Property<long>("Pool_id")
                        .HasColumnType("bigint");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Member", "Pool_id", "Balance", "Points");

                    b.ToTable("EventNominationPoolsWithdrawn");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.Staking.StakingEraPaidModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<long>("Era_index")
                        .HasColumnType("bigint");

                    b.Property<double>("Validator_payout")
                        .HasColumnType("double precision");

                    b.Property<double>("Remainder")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "Era_index", "Validator_payout", "Remainder");

                    b.ToTable("EventStakingEraPaid");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.System.SystemKilledAccountModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress");

                    b.ToTable("EventSystemKilledAccount");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Events.System.SystemNewAccountModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("ModuleEvent")
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("BlockchainName", "BlockId", "EventId", "ModuleName", "ModuleEvent", "AccountAddress");

                    b.ToTable("EventSystemNewAccount");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Extrinsics.ExtrinsicsInformationModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("ExtrinsicIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Charge")
                        .HasColumnType("double precision");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Fees")
                        .HasColumnType("double precision");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LifetimeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransactionVersion")
                        .HasColumnType("integer");

                    b.HasKey("BlockchainName", "BlockNumber", "ExtrinsicIndex");

                    b.HasIndex("LifetimeId");

                    b.ToTable("ExtrinsicsInformation");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Price.TokenPriceModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("BlockchainName", "Date");

                    b.ToTable("TokenPrices");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraLifetimeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockchainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("EndBlock")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsImmortal")
                        .HasColumnType("boolean");

                    b.Property<long?>("StartBlock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EraLifetime");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraStakersModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<int>("EraId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidatorAddress")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<BigInteger>("OwnStake")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("TotalStake")
                        .HasColumnType("numeric");

                    b.HasKey("BlockchainName", "EraId", "ValidatorAddress");

                    b.ToTable("EraStakersModels");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraStakersNominatorsModel", b =>
                {
                    b.Property<int>("EraStakersId")
                        .HasColumnType("integer");

                    b.Property<string>("NominatorAddress")
                        .HasColumnType("text");

                    b.Property<BigInteger>("ValueStake")
                        .HasColumnType("numeric");

                    b.HasKey("EraStakersId", "NominatorAddress");

                    b.ToTable("EraStakersNominatorsModel");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Version.PalletVersionModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<string>("PalletName")
                        .HasColumnType("text");

                    b.Property<int>("PalletVersion")
                        .HasColumnType("integer");

                    b.Property<long?>("BlockEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("BlockStart")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("SpecVersion")
                        .HasColumnType("bigint");

                    b.HasKey("BlockchainName", "PalletName", "PalletVersion");

                    b.ToTable("PalletVersionModels");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Version.SpecVersionModel", b =>
                {
                    b.Property<string>("BlockchainName")
                        .HasColumnType("text");

                    b.Property<long>("SpecVersion")
                        .HasColumnType("bigint");

                    b.Property<long?>("BlockEnd")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BlockEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BlockStart")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BlockStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MetadataVersion")
                        .HasColumnType("bigint");

                    b.HasKey("BlockchainName", "SpecVersion");

                    b.ToTable("SpecVersionModels");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Extrinsics.ExtrinsicsInformationModel", b =>
                {
                    b.HasOne("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraLifetimeModel", "Lifetime")
                        .WithMany()
                        .HasForeignKey("LifetimeId");

                    b.Navigation("Lifetime");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraStakersNominatorsModel", b =>
                {
                    b.HasOne("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraStakersModel", "EraStakers")
                        .WithMany("EraNominatorsVote")
                        .HasForeignKey("EraStakersId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EraStakers");
                });

            modelBuilder.Entity("Polkanalysis.Infrastructure.Database.Contracts.Model.Staking.EraStakersModel", b =>
                {
                    b.Navigation("EraNominatorsVote");
                });
#pragma warning restore 612, 618
        }
    }
}
