//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Polkanalysis.Infrastructure.Blockchain.Internal.Scan.Mapping;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3.Enums
{
    [DomainMapping("xcm/v3/junctions")]
    public enum Junctions
    {
        Here = 0,
        X1 = 1,
        X2 = 2,
        X3 = 3,
        X4 = 4,
        X5 = 5,
        X6 = 6,
        X7 = 7,
        X8 = 8
    }

    /// <summary>
    /// >> 16536 - Variant[xcm.v3.junctions.Junctions]
    /// </summary>
    public sealed class EnumJunctions : BaseEnumExt<Junctions, BaseVoid, EnumJunction, BaseTuple<EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction>, BaseTuple<EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction, EnumJunction>>
    {
    }
}