//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Polkanalysis.Infrastructure.Blockchain.Internal.Scan.Mapping;
using Substrate.NetApi.Model.Types.Base;
using System.Collections.Generic;

namespace Polkanalysis.Infrastructure.Blockchain.Contracts.Pallet.Xcm.v3.Enums
{
    [DomainMapping("xcm/v3/multiasset")]
    public enum MultiAssetFilter
    {
        Definite = 0,
        Wild = 1
    }

    /// <summary>
    /// >> 16798 - Variant[xcm.v3.multiasset.MultiAssetFilter]
    /// </summary>
    public sealed class EnumMultiAssetFilter : BaseEnumExt<MultiAssetFilter, MultiAssets, EnumWildMultiAsset>
    {
    }
}